#+TITLE: Depot
#+SETUPFILE: _setup.org

The documentation found herein follows the [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]]
principle, it /does not/ cover all of my configurations, so you are
invited to [[https://git.sr.ht/~grtcdr/dotfiles][browse the repository]] where the rest of my dotfiles live.

This project was made possible thanks to the [[https://www.gnu.org/software/emacs/][Emacs]] text editor, and
the [[https://orgmode.org/][Org Mode]] ecosystem - this is not to say that a literate
programming implementation is exclusive to these two, but I happen to
like their integration and extensibility.

Please note that a small portion of my configurations may contain
something adapted from someone's /[a]/ blog, /[b]/ video demonstration
or /[c]/ dotfiles.

* Explore

- [[file:dotfiles/sway/sway.org][sway]]

  A concoction of functionalism and elegance, making use of the bare
  minimum of software so as to achieve a coherent desktop environment
  without one being present.

  - [[file:dotfiles/sway/colorschemes.org][colorschemes]]
  - [[file:dotfiles/swaylock/swaylock.org][swaylock]]
  - [[file:dotfiles/mako/mako.org][mako]]

- [[file:dotfiles/zsh/zsh.org][zsh]]

  A short =zsh= configuration targeting simplicity.

- [[file:dotfiles/sh/doch.org][doch]]

  A shell script that lists and opens HTML/PDF files found within my
  =org-directory=.

- [[file:dotfiles/sh/startw.org][startw]]

  A shell script that intelligently starts =sway=, built with NVIDIA
  GPUs in mind.

- [[file:dotfiles/sh/mus.org][mus]]

  A shell script that automates the starting and stopping of =mpd= and
  =ncmpcpp=.
