#+TITLE: grtcdr: dotfiles
#+SETUPFILE: .setup.org
#+INCLUDE: .nav.org

* Preface
The documentation found herein follows the [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]]
principle.

It's only possible thanks to the [[https://www.gnu.org/software/emacs/][Emacs]] text editor, and the [[https://orgmode.org/][Org Mode]]
ecosystem.

The documentation does not cover all of my configurations. And so, I
invite you to [[https://git.sr.ht/~grtcdr/dotfiles][browse the repository]] where the rest of my dotfiles
live.

Please note that a small but significant portion of my configurations,
is a mold of what I've read in a blog, seen in a demonstration, or
just adapted from someone else's dotfiles.

You are free to use, modify and redistribute any of the material you
may find therein.

* Packages

- [[file:dots/sway/sway.org][sway]]: A concoction of subtlety and elegance, making use of the bare
  minimum of software so as to achieve a coherent desktop environment
  without one being present.
  - [[file:dots/swaylock/swaylock.org][swaylock]]: A =swaylock= configuration.
  - [[file:dots/mako/mako.org][mako]]: A =mako= configuration.
- [[file:dots/zsh/zsh.org][zsh]]: A straightforward =zsh= configuration that is optimized for speed.

* Scripts

- [[file:dots/sh/doch.org][doch]]: A shell =bemenu= script that lists and opens HTML/PDF files
  found within my =org-directory=.
- [[file:dots/sh/startw.org][startw]]: A shell script that intelligently starts =sway=.
- [[file:dots/sh/mus.org][mus]]: A shell script that automates the starting and stopping of
  =mpd= and =ncmpcpp=.
