#+TITLE: grtcdr/: dotfiles
#+INCLUDE: navbar.org
#+HTML_HEAD: <link rel="stylesheet" href="css/stylesheet.css">

* Preface

Ever since I had transitioned over to Emacs to obtain what (I felt)
Vim[fn:1] could not offer, I have made it my mission to finally configure the
editor to work for me. I had later stumbled upon [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]]. And
you know what? I am convinced, for the most part.

I have begun documenting many aspects of my day-to-day life, this
website and the documentation found herein is purely a result of the
hard work of others who have driven this philosophy forward. I am
grateful that Emacs adopts it in such an extensible and flexible
manner. I suppose this is the advantage of [[https://en.wikipedia.org/wiki/Lisp_(programming_language)][Lisp]] in general, and [[https://orgmode.org/][Org
Mode]] in particular.

The documentation does not cover everything I use, yet. So, I invite
you to [[https://git.sr.ht/~grtcdr/dotfiles][browse the repository]] where the rest of my dotfiles live.

You are *free* to use and modify any of the material you may find
therein — /Mi casa es su casa./

Do note that a small but significant portion of my configuration
files, is a mold of what I've read in a blog, seen in a demonstration,
or just adapted from someone else's dotfiles. In other words, not
every line is mine, but I always make sure to add my own personal
touch.

| Documentation | Description                                                                                                                                                  |
|---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [[file:rc/sway.org][Sway]]          | A concoction of subtlety and elegance, making use of the bear minimum of software so as to achieve a coherent desktop environment without one being present. |
| [[file:sh/doch.org][doch.sh]]       | A bemenu utility that can list and open any HTML/PDF file found within my =org-directory=.                                                                     |
| [[file:sh/startw.org][startw.sh]]     | A simple utility to start sway (with the appropriate flags).                                                                                                 |

* Footnotes

[fn:1] Vim and Emacs follow entirely different
philosophies, Vim is honest about its goals, while Emacs is
all-encompassing. I still use Vim daily, though.
