#+TITLE: dotfiles
#+SETUPFILE: .setup.org

* Preface

The documentation found herein follows the [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]]
principle.

It's only possible thanks to the [[https://www.gnu.org/software/emacs/][Emacs]] text editor, and the [[https://orgmode.org/][Org Mode]]
ecosystem.

The documentation does not cover all of my configurations. Hence, I
invite you to [[https://git.sr.ht/~grtcdr/dotfiles][browse the repository]] where the rest of my dotfiles
live.

Please note that a small but significant portion of my configurations,
is a mold of what I've read in a blog, seen in a demonstration, or
just adapted from someone else's dotfiles.

-----

- [[file:dots/sway/sway.org][sway]]

  A concoction of functionalism and elegance, making use of the bare
  minimum of software so as to achieve a coherent desktop environment
  without one being present.

  - [[file:dots/sway/colorschemes.org][colorschemes]]
  - [[file:dots/swaylock/swaylock.org][swaylock]]
  - [[file:dots/mako/mako.org][mako]]

- [[file:dots/zsh/zsh.org][zsh]]

  A short =zsh= configuration targeting simplicity.

- [[file:dots/sh/doch.org][doch]]

  A shell script that lists and opens HTML/PDF files found within my
  =org-directory=.

- [[file:dots/sh/startw.org][startw]]

  A shell script that intelligently starts =sway=.

- [[file:dots/sh/mus.org][mus]]

  A shell script that automates the starting and stopping of =mpd= and
  =ncmpcpp=.
