#+TITLE: grtcdr's dotfiles
#+INCLUDE: navbar.org
#+OPTIONS: html-postamble:nil num:nil toc:nil

* Preface

Ever since I had transitioned over to Emacs to obtain what (I felt)
Vim could not offer, I have made it my mission to finally configure the
editor to work for me, and so I stumbled upon literal programming. And
you know what? I am convinced, for the most part.

I have began documenting many aspects of my day to day life, and this
website is purely a result of the hard work of others who have
pioneered this philosophy. I am grateful that Emacs adopts it in such
an extensible and flexible manner. I suppose this is the advantage of
Lisp in general.

-----

* Literate dotfiles

The following is a list of documented dotfiles, that I hope you may
extract something useful out of. Feel free to borrow, take,
whatever. /Mi casa es su casa./

The documentation does not cover everything, yet. So, I invite you to
[[https://git.sr.ht/~grtcdr/dotfiles][take a look at the repository]] where all of my dotfiles live.

** [[file:rc/sway.org][sway]]

A concoction of subtlety and elegance, making use of the bear minimum
of software so as to achieve a coherent desktop environment without
one being present.

Features:
+ [[https://www.nordtheme.com/][Nord]], as the palette.
+ [[https://typeof.net/Iosevka/][Iosevka Aile]], as the font.

* Literate shell scripts

** [[file:sh/doch.org][doch]]

A bemenu utility that can list and open any HTML/PDF file found within
my =org-directory=.

** [[file:sh/startw.org][startw]]

A bemenu utility that can list and open any HTML/PDF file found within
my =org-directory=.
