#+TITLE: grtcdr's dotfiles
#+INCLUDE: navbar.org
#+OPTIONS: html-postamble:nil num:nil toc:nil

* Preface

Ever since I had transitioned over to Emacs to obtain what (I felt)
Vim[fn:1] could not offer, I have made it my mission to finally configure the
editor to work for me. I had later stumbled upon [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]]. And
you know what? I am convinced, for the most part.

I have begun documenting many aspects of my day to day life, and this
website is purely a result of the hard work of others who have
driven this philosophy forward. I am grateful that Emacs adopts it in such
an extensible and flexible manner. I suppose this is the advantage of
[[https://en.wikipedia.org/wiki/Lisp_(programming_language)][Lisp]] in general, and [[https://orgmode.org/][Org Mode]] in particular.

-----

The following is a list of documented dotfiles, that I hope you may
extract something useful out of.

A small but significant portion of my configurations is a mold of
what I've read in a blog, seen in a demonstration, or took from
someone's neatly organized dotfiles.

The documentation does not cover everything, yet. So, I invite you to
[[https://git.sr.ht/~grtcdr/dotfiles][take a look at the repository]] where all of my dotfiles live.

You are *free* to use and modify any of the material you may find therein.

/Mi casa es su casa./

* Literate dotfiles

** [[file:rc/sway.org][sway]]

A concoction of subtlety and elegance, making use of the bear minimum
of software so as to achieve a coherent desktop environment without
one being present.

Features:
+ [[https://www.nordtheme.com/][Nord]], as the palette.
+ [[https://typeof.net/Iosevka/][Iosevka Aile]], as the font.

* Literate shell scripts

** [[file:sh/doch.org][doch]]

A bemenu utility that can list and open any HTML/PDF file found within
my =org-directory=.

** [[file:sh/startw.org][startw]]

A simple utility to start sway (with the appropriate flags).

* Footnotes

[fn:1] Vim and Emacs follow entirely different
philosophies, Vim is honest about its goals, while Emacs is
all-encompassing. I still use Vim daily, though.
