#+TITLE: Musichronicle
#+SETUPFILE: _setup.org

My intentions with this small project is to document the music that
I've recently come to adore, and to share these beautiful sounds with
the rest of you!

I usually have trouble recalling the music I'm fond of, and the
artists that express with sounds, what I couldn't with words. I hope
this project succeeds at keeping track of these very artists, and I
look forward to continuously updating this page as time goes on.

* 2022
** Son Lux - Tomorrows :experimental:

I was recently reintroduced to [[https://musicbrainz.org/artist/afcd292c-3c1e-4708-af4a-991aadf957e4][Son Lux]], a band of three extremely
talented individuals, by a couple of relatives who went to see their
concert. Although I didn't attend, I'm glad to have been reminded of
Son Lux -- it had been four whole years since I last listened to their
works.

This album is no different, every single track is /simply terrific/.

The element that makes Son Lux stand out the most in this particular
genre, is the distinctiveness of their sound, which can be considered
as having been meticulously engineered to serve the purpose of
exposing you to something you never imagined could exist, all the
while conforming to a rather sophisticated musical structure.
