Hola!

* Setup

Clone the repository and its [[file:.gitmodules][submodules]]:

#+begin_example
git clone --recursive https://github.com/grtcdr/grtcdr.github.io.git grtcdr.tn
#+end_example

* Reproducing

If you wish to reproduce this website locally, there are two requirements:
+ an installation of [[https://www.gnu.org/software/emacs/][GNU Emacs]]
+ and [[https://lesscss.org/][lesscss]]

You can then export each file individually, or make use of my
[[https://git.sr.ht/~grtcdr/dotfiles/tree/main/item/emacs/.config/emacs/lisp/grt-publish.el][org-publish-project-alist]] configuration that automatically builds the
whole website for you.

I have written [[https://grtcdr.github.io/posts/building-a-website-with-emacs.html][a post]] that answers the "why" and "how" of
~org-publish-project-alist~.

* Development

In order to fully utilize the website during development, you should
serve the ~public~ directory with a web server, e.g. [[https://github.com/svenstaro/miniserve][miniserve]]:

#+begin_src sh
cd grtcdr.tn
miniserve public
#+end_src

* Structure

This website utilizes the following submodules to achieve a more
modular and flexible structure:

- [[https://git.sr.ht/~grtcdr/dotfiles][dotfiles]], a repository that hosts my personal configuration files, some of which are documented.
- [[https://github.com/grtcdr/resume][resume]], a repository that hosts my résumé.

This allows me to work on these two projects independently, whilst
maintaining their individual composability.

For more information on submodules, visit this [[https://git-scm.com/book/en/v2/Git-Tools-Submodules][manual]].

* Copying

The content in this site is [[file:COPYING/CONTENT.txt][CC-BY-SA 2.0]] — The source code is [[file:COPYING/SOURCE.txt][MIT]].
