This is the source for [[https://grtcdr.github.io][grtcdr.github.io]].

* How it works

These files are compiled and placed in the ~public~ directory.

With every commit, CI pulls the changes, creates a new commit in the
~gh-pages~ branch and deploys it.

Jekyll is configured not to interfere with this process, and this is
done by creating a ~.nojekyll~ file at the root of the project.

* Setup

Clone the repository and its [[file:.gitmodules][submodules]]:

#+begin_example
git clone --recursive https://github.com/grtcdr/site.org.git
#+end_example

* Reproducing

If you wish to reproduce this website locally, there are two requirements:
+ an installation of [[https://www.gnu.org/software/emacs/][GNU Emacs]]
+ and [[https://lesscss.org/][lesscss]]

You can then export each file individually, or make use of my
[[https://git.sr.ht/~grtcdr/dotfiles/tree/main/item/emacs/.config/emacs/lisp/grt-publish.el][org-publish-project-alist]] configuration that automatically builds the
whole website for you.

I have written [[https://grtcdr.github.io/posts/building-a-website-with-emacs.html][a post]] that answers the "why" and "how" of
~org-publish-project-alist~.

* Structure

This website utilizes the following submodules to achieve a more
modular and flexible structure:

- [[https://git.sr.ht/~grtcdr/dotfiles][dotfiles]], a repository that hosts my personal configuration files, some of which are documented.
- [[https://github.com/grtcdr/resume][resume]], a repository that hosts my résumé.

This allows me to work on these two projects independently, whilst
maintaining their individual composability.

For more information on submodules, visit this [[https://git-scm.com/book/en/v2/Git-Tools-Submodules][manual]].

* Copying

The contents of [[https://github.com/grtcdr/site.org][this repository]] is [[https://creativecommons.org/licenses/by-sa/2.0/][CC-BY-SA 2.0]], the source code is
[[file:COPYING][MIT]].
