Hola!

This repository stores the source code of grtcdr.github.io (grtcdr.tn).

* Setup

Clone the repository and its [[file:.gitmodules][submodules]]:

#+begin_example
git clone --recursive https://github.com/grtcdr/grtcdr.github.io.git grtcdr.tn
#+end_example

* Reproducing

If you wish to reproduce this website locally, the most overarching dependency is [[https://www.gnu.org/software/emacs/][GNU Emacs]].

After that, you should proceed by installing the packages listed in [[file:package.json][package.json]].

You'll also want to install [[https://www.gnu.org/software/make/][GNU Make]] to reap the benefits of the [[https://en.wikipedia.org/wiki/Build_automation][build system]] in use.
  
* Building

From the command-line, position yourself at the root of this project, and run the following:

#+begin_src sh
make
#+end_src

* Development

In order to fully utilize the website during development, you should serve the ~public~ directory with a web server, e.g. [[https://github.com/svenstaro/miniserve][miniserve]]:

#+begin_src sh
cd grtcdr.tn
miniserve public
#+end_src

* Structure

This skeleton of this website is defined in [[file:publish.el][publish.el]] and it utilizes the following submodules to achieve a more modular structure:

- [[https://git.sr.ht/~grtcdr/dotfiles][dotfiles]], a repository that hosts my personal configuration files, many of which are documented.
- [[https://github.com/grtcdr/resume][resume]], a repository that hosts my résumé.

This allows me to work on these two projects independently, whilst maintaining their individual composability.

* Copying

The content in this site is [[file:COPYING/CONTENT.txt][CC-BY-SA 2.0]] -- The source code is [[file:COPYING/SOURCE.txt][MIT]].
