* Structure

This project uses [[file:lisp/op-publish.el][a publishing script]], among other modules, to define
the components which are then used to generate the website. Emacs Lisp
files inside the [[file:lisp/][lisp]] directory all share one similarity, the =op=
prefix, a /local/ convention and a reference to the initials of the
=ox-publish= library.

* Setup

Clone the repository and its [[file:.gitmodules][submodules]]:

#+begin_example
git clone --recursive https://github.com/grtcdr/grtcdr.github.io.git grtcdr.tn
#+end_example

* Reproducing

If you wish to reproduce this site locally, the most overarching
dependency is [[https://www.gnu.org/software/emacs/][GNU Emacs]].

Once you've set that up, you should install this project's development
dependencies. To do that, position yourself at the project root,
i.e. the location where you cloned this repository, and then run =npm
install=.

You'll also want to install [[https://www.gnu.org/software/make/][GNU Make]] to reap the benefits of the build
system in use.
  
* Building

From the command-line, position yourself at the root of the project
and run the =make= command.

* Development

In order to fully utilize the site during development, you should
serve the =public= directory with a web server. This project uses
[[https://github.com/svenstaro/miniserve][miniserve]] by default and thus has a recipe to quickly serve the site:

#+begin_src sh
make serve
#+end_src

* Deployment

This site is hosted on GitHub Pages, and utilizes a [[file:.github/workflows/pages.yml][CI workflow]] to
build and deploy the site with every commit made to the default branch.

The workflow is split into two major jobs: *build* and *deploy*.

1. *build* is responsible for producing the site; the output of this
   process generates an artifact, the =public= directory.

2. *deploy* receives this artifact and proceeds to deploy it to the
   GitHub Pages servers.

* Copying

The content and source code of this site is licensed under the
[[https://creativecommons.org/licenses/by-sa/2.0/][CC-BY-SA 2.0]] and [[file:COPYING][ISC]] licenses respectively.
