This is the source for [[https://grtcdr.github.io][grtcdr.github.io]].

After processing, the output is placed in a [[https://github.com/grtcdr/grtcdr.github.io][different repository]],
whose content is readable by the browser.

* Setup

Clone the repository and its [[file:.gitmodules][submodules]]:

#+begin_example
git clone --recursive https://github.com/grtcdr/site.org.git
#+end_example

* Reproducing

If you wish to reproduce this website locally, the only requirement to
do so, is an installation of [[https://www.gnu.org/software/emacs/][GNU Emacs]].

You can then export each file individually, or make use of my
[[https://git.sr.ht/~grtcdr/dotfiles/tree/main/item/emacs/.config/emacs/lisp/grt-publish.el][org-publish-project-alist]] configuration that automatically builds the
whole website for you.

I have written [[https://grtcdr.github.io/posts/purely-org-site.html][a post]] that answers the "why" and "how" of
org-publish-project-alist.

* Structure

This website utilizes the following submodules to achieve a more
modular and flexible structure:
- [[https://git.sr.ht/~grtcdr/dotfiles][dotfiles]]
- [[https://github.com/grtcdr/resume][resume]]

This allows me to work on these two projects separately, maintaining composability.

For more information on submodules, visit this [[https://git-scm.com/book/en/v2/Git-Tools-Submodules][manual]].

* Copying

- The contents of [[https://github.com/grtcdr/site.org][this repository]], and the [[https://github.com/grtcdr/grtcdr.github.io][grtcdr.github.io repository]] are [[https://creativecommons.org/licenses/by-sa/2.0/][CC-BY-SA 2.0]]. The source code of both is licensed under the [[file:COPYING][MIT license]].
