#+TITLE: Aziz Ben Ali
#+SETUPFILE: _setup.org
#+OPTIONS: prop:t tasks:nil

#+begin_quote
You can view my résumé in [[file:data/resume.pdf][PDF format]].
#+end_quote

* Education

** École Supérieur Privée d'Ingénierie et de Technologies
:PROPERTIES:
:STUDY: Computer Science
:START_DATE: Sep. 2019
:END_DATE: Present
:END:

* Employers

** Arab Tunisian Bank
:PROPERTIES:
:POSITION: Software Developer
:TYPE: Internship
:LOCATION: Ariana, Tunisia
:START_DATE: Jul. 11, 2022
:END_DATE: Present
:END:

** HLi Group
:PROPERTIES:
:POSITION: Web Developer
:TYPE: Internship
:LOCATION: Ariana, Tunisia
:START_DATE: Jul. 2021
:END_DATE: Sep. 2021
:END:

+ Improved and reworked internal .NET web applications, front- and back-end.

** Thermecatex
:PROPERTIES:
:POSITION: Information Technology
:TYPE: Internship
:LOCATION: Tunis, Tunisia
:START_DATE: Aug. 2018
:END_DATE: Sep. 2018
:END:

+ Helped develop and migrate to a new inventory system, a digitalized version of its predecessor.

* Open Source Projects

In my spare time, I like to give back to the open source community. I’ve also authored my own tools over the years.

** macchina
A system information frontend, with an (unhealthy) emphasis on performance. [[https://github.com/Macchina-CLI/macchina][~GitHub]]

** libmacchina
A library providing access to all sorts of system information. [[https://github.com/Macchina-CLI/libmacchina][~GitHub]]

** citron
A lightweight program providing system data via on-demand notifications. [[https://sr.ht/~grtcdr/citron][~SourceHut]]

** paspio
A library and command-line utility for calculating password entropy. [[https://sr.ht/~grtcdr/paspio][~SourceHut]]


* Skills
** Programming Languages

- Proficient in Rust and (PL/)SQL.
- Comfortable with PHP and shell scripting.
- Acquainted with Python, Ruby and Java.

** Tools

- Proficient in Linux, i.e. Ubuntu and Arch. I've self-hosted an internet-facing server and exposed various web applications through it.
- Comfortable with Git, which I use to version control my personal and public projects.
- Comfortable with PlantUML, which I utilize to create plain-text, reproducible and version-controlled UML diagrams.

** Documentation and markup languages

- Proficient in Markdown.
- Comfortable with Org Mode and HTML.
- Acquainted with LaTeX and Asciidoctor.

** Languages
- English, fluent
- French, conversational
- Arabic, native
