#+TITLE: grtcdr/sh/startw: A utility to start Sway intelligently
#+STARTUP: hideblocks
#+OPTIONS: html-postamble:nil
#+INCLUDE: ../navbar.org
#+PROPERTY: header-args :tangle ~/.local/bin/startw :tangle-mode (identity #o744)
#+HTML_HEAD: <link rel="stylesheet" href="../css/stylesheet.css">

* About
A utility to start Sway intelligently.

* Features

If NVIDIA kernel modules are loaded (meaning an NVIDIA graphics card
is present and active), sway will launch with the =--unsupported-gpu=
flag. Otherwise, it starts normally, i.e. with no extra flags.

* Use case
This script is intended to start automatically after a successful TTY login. To achieve this, one must append the following to their =.bash_profile= (bash), or =.zprofile= (zsh):

#+begin_src bash :tangle no
  source "$HOME"/.local/bin/startw
#+end_src

To work around [[https://github.com/tmux/tmux][tmux]] loading this script for every new client, the
script should only be sourced when the =TMUX= variable is not set, so
you might prefer this instead:

#+begin_src bash :tangle no
  [[ -z $TMUX ]] && source "$HOME"/.local/bin/startw
#+end_src

* Source
1. [@1] Define local variables used within the script:

   #+begin_src bash :shebang "#!/usr/bin/env bash"
     TIMEOUT=4
     JAVA_GUI_SUPPORT="yes"
   #+end_src

   - =TIMEOUT= is the number of seconds this utility waits before cancelling input[fn:4].
   - =JAVA_GUI_SUPPORT= is intended to workaround rendering issues[fn:2] of certain Java GUI applications.

2. [@2] Define the function which will start sway with the appropriate flag:
#+begin_src bash
  launch_sway() {
      HAS_NVIDIA=$(lsmod | grep -c nvidia)
      case $JAVA_GUI_SUPPORT in
	  "Y" | "y" | "YES" | "yes") export _JAVA_AWT_WM_NONREPARENTING=1;;
      esac

      if [ "$HAS_NVIDIA" -eq 0 ]; then
	  exec sway
      else
	  exec sway --unsupported-gpu
      fi
  }
#+end_src

3. [@3] Verify that a graphical session hasn't been started already[fn:1]:
#+begin_src bash
  check_console() {
      if [ -n "$DISPLAY" ] && [ "$(tty)" != "/dev/tty1" ]; then
	  echo "Already in a graphical session."
	  exit 1
      fi
  }
#+end_src

4. [@4] Define the prompter:

#+begin_src bash
  prompt() {
      check_console

      echo "Would you like to start sway?\n"
      echo "Press <Ctrl-C> to cancel."
      read -rst $TIMEOUT -n 1 IN

      case $IN in
	  [Yy]* | "") launch_sway;;
      esac
  }
#+end_src

5. [@5] Call the prompter:
#+begin_src bash
  prompt
#+end_src

* Footnotes
[fn:1] Adapted from [[https://wiki.archlinux.org/title/Sway#Automatically_on_TTY_login][this page in the Arch Wiki.]]
[fn:2] Setting =_JAVA_AWT_WM_NONPARENTING= to =1= essentially makes Java GUI applcications behave well in a non-reparenting tiling window manager environment.
[fn:3] IntelliJ IDEA and other JetBrains products are affected by this bug.
[fn:4] If the expected input (pressing y) isn't provided within 3 seconds, =startw= will back off, letting you continue to use the TTY.
