name: Publish

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.2

      - name: Install documentation compilers
        run: apt install -y graphviz plantuml
        
      - name: Run pre-hooks
        env:
          PREFIX: ${{ format('https://media.githubusercontent.com/media/{0}/{1}/assets/images', github.repository, github.ref_name) }}
        run: |
          # The purpose of this command is to find and replace the URLs
          # of local images to the URLs that Git LFS assigns to them.
          find src/posts -type f -exec sed -i "s-/assets/images-${PREFIX}-g" {} +

      - name: Build website
        run: make

      - name: Copy .well-known
        run: cp -R .well-known public

      - name: Upload website blob
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
