name: Publish the site

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: "Build the site"
    strategy:
      matrix:
        dependencies: [graphviz plantuml]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout submodules
        run: |
          # Pull every submodule
          git submodule update --init --recursive --remote
          # Checkout the default branch (so as to reattach HEAD) for
          # the "dotfiles" submodule
          cd src/dotfiles
          git checkout main
          git pull

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v1

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src/cv
          root_file: cv.tex

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: snapshot

      - name: Install dependencies
        run: sudo apt-get install -y ${{ matrix.dependencies }}

      - name: Run pre-hooks
        env:
          PREFIX: ${{ format('https://media.githubusercontent.com/media/{0}/{1}/assets/images', github.repository, github.ref_name) }}
        run: |
          # Find and replace the URLs of local images to the URLs that
          # Git LFS assigns to them.
          find src/posts -type f -exec sed -Ei "/.(png|jpe?g)/s-/assets/images-${PREFIX}-g" {} +

      - name: Build the website
        env:
          WITH_PDF: "false"
        run: make

      - name: Upload website blob
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    name: "Deploy the site"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
